[package]
name = "day3"
version = "0.1.0"
authors = ["Marek Vrbka <469025@mail.muni.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
